### ISSUE TITLE
tin.heightAt(fractional) sometimes returns undefined

### ISSUE THREAD

**Issue by Fil** [mapbox/delatin#1]
~~~
tin.heightAt(0.5, 0.5) = 106 
tin.heightAt(0.4, 0.2) = undefined
~~~~
https://observablehq.com/d/d7308c628ac58d15

Also, you'll see in that notebook that loading the module was a bit difficult.

As a side note, I would encourage you to rename "heights" into "values", because it clashes with "height".

Other than that: 👍!!

**Comment by Fil** [comment]
Oh I get it, https://github.com/mapbox/delatin/blob/master/index.js#L47 returns "something" (not related to the actual geometry) for `xy=(0.5,0.5)` only because `width*x+y` happens to be an integer result.

**Comment by mourner** [comment]
👍 made some clarifications in 7b8e3b5

**Comment by mourner** [comment]
> Also, you'll see in that notebook that loading the module was a bit difficult.

Yeah, I noticed that recently too, although that's an Observable limitation (static imports support would be great). I should probably add a minified UMD build for a classic `require` anyway.
